steps:
  # 必要なファイルを一時ディレクトリにコピー
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /workspace/build/libs /workspace/build/apps/backend
        cp ./* /workspace/build/
        cp -R libs/* /workspace/build/libs/
        cp -R apps/backend/* /workspace/build/apps/backend/

  # Docker イメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/tidb-prisma-gql-monorepo/backend'
      - '-f'
      - '/workspace/build/apps/backend/Dockerfile'
      - '/workspace/build'

  # Docker イメージを GCR にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tidb-prisma-gql-monorepo/backend']

  # Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=gcr.io/tidb-prisma-gql-monorepo/backend'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/tidb-prisma-gql-monorepo/backend'
