name: Deploy Frontend to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/frontend/**"

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      # 必要なファイルをコピー
      - name: Prepare Build Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/build/libs
          mkdir -p $GITHUB_WORKSPACE/build/apps/frontend
          cp -r ./libs/* $GITHUB_WORKSPACE/build/libs/
          cp -r ./apps/frontend/* $GITHUB_WORKSPACE/build/apps/frontend
          cp ./pnpm-workspace.yaml $GITHUB_WORKSPACE/build/
          cp ./package.json ./pnpm-lock.yaml ./turbo.json $GITHUB_WORKSPACE/build/

      - name: Prepare .env from GitHub Secret
        run: echo "${{ secrets.ENV_PROD }}" > $GITHUB_WORKSPACE/build/apps/frontend/.env

      # Docker イメージをビルドして Artifact Registry にプッシュ
      - name: Build and Push Docker Image
        run: |
          docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend-repo/frontend \
            -f $GITHUB_WORKSPACE/build/apps/frontend/Dockerfile \
            $GITHUB_WORKSPACE/build/
          docker push asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend-repo/frontend

      # Cloud Run にデプロイ
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend \
            --image asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend-repo/frontend \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated
